### ISSUE TITLE
Rename repo for convention

### ISSUE THREAD

**Issue by pranaygp** [developermo-de/hackerMode#1]
Could you please rename `hackerMode` to `hackermode`. It helps maintain convention (especially given that the main repo is `developermode.github.io`) and let's the organization repo listing page look better. :smile:

**Comment by modi95** [comment]
Could we instead switch to uppercase M?
I'm almost certainly going to have an uppercase M on the website so that it's easier to read.

**Comment by pranaygp** [comment]
I think we should just let every blogger do this however they want to.

**Comment by pranaygp** [comment]
Another thing about doing it as so it that we can keep our doc to 

> Here are our 3 Golden Rules:
> - *mo.de Domain
> - Good Design
> - Link to parent domain

**Comment by modi95** [comment]
Okay then. Closing this issue.
And I'll create a wiki page for it.
